### PR TITLE
IT-36016 / Multiservice_cm: Get rid of what's not needed within apscli and piper API

### PR DESCRIPTION
**Pull request by apgsga-jhe**
In order to make the review easier, I'll do different pull request one after each other, that means I'll probably quickly merge ;)

This pull request is specific for IT-36016.  Following tickets will be done within next steps (and next pull request)  :

- https://jira.apgsga.ch/browse/IT-36033
- https://jira.apgsga.ch/browse/IT-36032
- https://jira.apgsga.ch/browse/IT-35944
- https://jira.apgsga.ch/browse/IT-35947

Following options have been kept for apscli:

```
			h longOpt: 'help', 'Show usage information', required: false
			e longOpt: "exists", args:1, argName: 'patchNumber', 'True resp. false if Patch of the <patchNumber> exists or not', required: false
			f longOpt: 'findById', args:2, valueSeparator: ",", argName: 'patchNumber,directory','Retrieve a Patch with the <patchNumber> to a <directory>', required: false
			sa longOpt: 'save', args:1, argName: 'patchFile', 'Saves a <patchFile> to the server, which starts the Patch Pipeline', required: false
			// TODO (CHE,13.9) Get rid of the component parameter, needs to be coordinated with current Patch System (PatchOMat)
			sta longOpt: 'stateChange', args:3, valueSeparator: ",", argName: 'patchNumber,toState,component', 'Notfiy State Change for a Patch with <patchNumber> to <toState> to a <component> , where <component> can only be aps ', required: false
			cm longOpt: 'cleanLocalMavenRepo', "Clean local Maven Repo used bei service", required: false
			log longOpt: 'log', args:1, argName: 'patchFile', 'Log a patch steps for a patch', required: false
			adp longOpt: 'assembleDeployPipeline', args:1, argName: 'target', "start an assembleAndDeploy pipeline for the given target", required: false
```

"e" and "f":  could be useful for https://jira.apgsga.ch/browse/IT-36032, not 100% sure yet.

"log": depending on how we'll show the info within the future GUI, we might remove it, but for now I would prefer to keep it.

### CODE REVIEW

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe looks good , how about the test code?

I removed tests which were related with options not needed anymore, I hope I didn't forget any (everything ran fine on my machine)

**Comment by chhex** [comment]
@apgsga-jhe  naturally you run the tests locally

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe naturally you run the tests locally ...all the tests of piper...

@chhex : Mmhh, which tests did you mean? What I also quickly did is to install both (cli and piper) on my VM, and try to execute apscli.sh , just to ensure it at least gets correctly instantiated. But yeah of course, I didn't extensively test piper yet.

**Comment by chhex** [comment]
@apgsga-jhe  the junit tests , when you do a cd ~../piper ; ./gradlew clean build publishToMavenLocal --info

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe the junit tests , when you do a cd ~../piper ; ./gradlew clean build publishToMavenLocal --info

@chhex : ok ok, yep they ran fine as well.

**Pull request merged**
