### PR TITLE
IT-36397 / Piper package does'nt provide  github.repo.url default

### PR DESCRIPTION
**Pull request by apgsga-jhe**
@chhex
Here we go, ready for a review .... Probably things are missing on the Interface (PatchSystemMetaInfoPersistence), but as discussed, we'll implement what we'll need ... when we'll need it.
You shouldn't find any reference to TargetSystemMapping anymore, nor any TargetSystemMappings.json file.
All tests running fine from IntelliJ.

### CODE REVIEW

**Review by chhex — COMMENTED** [review]
@apgsga-jhe Had a quick look: Very cool, for a first go this is certainly the way to. 
You can evolve as Requirements add up.

**Comment by apgsga-jhe** [comment]
> @apgsga-jhe Had a quick look: Very cool, for a first go this is certainly the way to.
> You can evolve as Requirements add up.

@chhex : Cool thanks. Yep exactly, this will certainly evolve, which shouldn't be a problem. Perfect, I'll then merge today.

**Comment by apgsga-uge** [comment]
well, Christoph was faster - as usual ;-)
looks good :-)
nothing to add from my side - go on merging...

**Comment by apgsga-jhe** [comment]
@apgsga-uge : Cool thanks. Actually, this was the purpose of the call of yesterday .... or call of today ;) .... I'll phone you after Interapp meeting.

**Pull request merged**
